gen_data_dir: "data/test"
eval_data_dir: "data/test"
gen_output_dir: "outputs"
eval_output_dir: "outputs"
overwrite_evaluations: False
overwrite_generations: False

tasks: 
  - name: zero_shot
    subtasks:
      flores.en-zh:
        eval_args:
          metrics:
            bleu:
              tokenizer: zh
      flores.en-de:
      flores.zh-en:
      flores.de-en:
    metrics:
      chrf:
      bleu:
        tokenizer: zh
      comet:
        batch_size: 16
        
models:
  - name: gpt-4o-mini
    model_platform: openai
    model_name: gpt-4o-mini
    arguments:
      max_tokens: 4096
      batch_size: 8
      retry_max_attempts: 200