# API
OPENAI_API_KEY = "sk-xx"
OPENAI_API_BASE_URL = "https:xx"
DASHSCOPE_API_KEY = "sk-xx"
DASHSCOPE_API_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
DEEPSEEK_API_KEY = "sk-xx"
DEEPSEEK_API_BASE_URL = "https://api.deepseek.com"

API_KEY_DICT = {
    'OPENAI': OPENAI_API_KEY,
    'QWEN': DASHSCOPE_API_KEY,
    'DEEPSEEK': DEEPSEEK_API_KEY,
}

BASE_URL_DICT = {
    'OPENAI': OPENAI_API_BASE_URL,
    'QWEN': DASHSCOPE_API_BASE_URL,
    'DEEPSEEK': DEEPSEEK_API_BASE_URL,
}


LOG_DIR='logs'
SAVE_DIR="outputs" 
FEW_SHOT_PATH="data/human_written_data"

# Loop threshold
OVERALL_SCORE_THRESHOLD=26
LOOP_THRESHOLD=6
MAXIMUM_TIME_THRESHOLD=300
RETRY_THRESHOLD=20

# Concurrent threads
MAX_WORKERS=8